<table class="table table-responsive">
  <thead>
    <th></th>
    <th>Gramos</th>
    <th>Porcentajes</th>
    <th>Calorías</th>
  </thead>
  <tbody>
    <tr>
      <th>Proteína</th>
    </tr>
    <tr>
      <th>HdC</th>
    </tr>
    <tr>
      <th>Lípidos</th>
    </tr>
    <tr>
      <th>Total</th>
    </tr>
  </tbody>
</table>